Navigation banner
matteoTomicic/criminals-clique pull request #6
Opened 2022-07-19 11:47 UTC by matteoTomicic

2022-07-26 06:40 UTC, skovacicI3 requested changes

2022-09-14 08:31 UTC, aduda091 commented on pages/index.tsx
> +            <div />
prazan div?

2022-09-14 08:33 UTC, aduda091 commented on src/components/Globals/Navigation/Navigation.tsx
> +        document.body.classList.toggle('disable-scroll', isOpen);
ako ćeš, ovakve stvari ful dobro radi paket [body-scroll-lock](https://www.npmjs.com/package/body-scroll-lock)

2022-09-14 08:35 UTC, aduda091 commented on src/components/UI/HamburgerMenu/HamburgerMenu.tsx
> +    const [active, setActive] = useReducer((state) => !state, false);
znatiželja, zašto use reducer za običan boolean :D nisam ga do sad nikad koristio (jednom sam krenuo pa odustao radi typescript issues, wasn't worth it)

2022-09-14 12:40 UTC, matteoTomicic commented on src/components/UI/HamburgerMenu/HamburgerMenu.tsx
> +    const [active, setActive] = useReducer((state) => !state, false);
a ono, show off :D

2022-09-21 10:48 UTC, matteoTomicic commented on src/components/Globals/Navigation/Navigation.tsx
> +        document.body.classList.toggle('disable-scroll', isOpen);
to mi treba samo na jedom mjestu, tako da za sad necu ubacivati paket. :)
ako mi nekad bude trebalo za vise toga, imat cu na umu. tnx :)

2022-09-21 10:53 UTC, merged